import 'dart:io';
import 'dart:typed_data';

import 'package:kernel/binary/ast_from_binary.dart';
import 'package:kernel/kernel.dart';
import 'package:vm/metadata/closure_id.dart';
import 'package:vm/metadata/direct_call.dart';
import 'package:vm/metadata/inferred_type.dart';
import 'package:vm/metadata/loading_units.dart';
import 'package:vm/metadata/obfuscation_prohibitions.dart';
import 'package:vm/metadata/procedure_attributes.dart';
import 'package:vm/metadata/table_selector.dart';
import 'package:vm/metadata/unboxing_info.dart';
import 'package:vm/metadata/unreachable.dart';
import 'package:vm/modular/metadata/call_site_attributes.dart';

/// Reads the kernel snapshot at [path].
///
/// The release snapshot handed to us has already been through the front end's
/// global type flow analysis, whose results - inferred types, direct call
/// targets, dispatch tables, and the rest - ride along as metadata sections.
/// The kernel reader only keeps a metadata section when a repository claiming
/// its tag is registered up front, and the writer only writes the sections it
/// kept, so a snapshot read without these repositories comes out the other
/// side with the analysis thrown away and is compiled to noticeably worse
/// machine code.
///
/// The registration order is the order the sections are written back out in,
/// and it matters: a metadata section that belongs to the component as a whole
/// is written when the component is, so the first such repository registered
/// is the one whose payload lands at offset zero. `gen_snapshot` looks the
/// component's table selectors up by feeding the payload offset it just found
/// back in as a node offset, which only resolves for the payload at offset
/// zero - so the order below is the one the front end writes, with the table
/// selectors ahead of the other two component wide sections.
Component readSnapshot(String path) {
  final component = Component();
  for (final MetadataRepository<Object?> repository
      in <MetadataRepository<Object?>>[
        CallSiteAttributesMetadataRepository(),
        DirectCallMetadataRepository(),
        InferredTypeMetadataRepository(),
        InferredArgTypeMetadataRepository(),
        InferredReturnTypeMetadataRepository(),
        UnreachableNodeMetadataRepository(),
        ProcedureAttributesMetadataRepository(),
        TableSelectorMetadataRepository(),
        ClosureIdMetadataRepository(),
        UnboxingInfoMetadataRepository(),
        ObfuscationProhibitionsMetadataRepository(),
        LoadingUnitsMetadataRepository(),
      ]) {
    component.addMetadataRepository(repository);
  }

  // The plain [BinaryBuilder] skips the metadata section outright; only this
  // subclass hands the sections to the registered repositories.
  final Uint8List bytes = File(path).readAsBytesSync();
  BinaryBuilderWithMetadata(bytes, filename: path).readComponent(component);
  return component;
}

/// Writes [component] back out as a kernel snapshot.
Future<void> writeSnapshot(Component component, String path) =>
    writeComponentToBinary(component, path);

/// Forgets the constant values the type flow analysis recorded for [values].
///
/// The analysis notes when an expression or a member always evaluates to a
/// particular constant, and `gen_snapshot` folds those constants back into the
/// code it generates. For a string that has just been replaced by a runtime
/// lookup that would put the plaintext straight back into the snapshot - the
/// program still behaves the same, it is just no longer obfuscated - so the
/// recorded constant has to go. The inferred type itself is kept.
void dropRecordedStringConstants(Component component, Set<String> values) {
  if (values.isEmpty) {
    return;
  }
  for (final String tag in const <String>[
    InferredTypeMetadataRepository.repositoryTag,
    InferredArgTypeMetadataRepository.repositoryTag,
    InferredReturnTypeMetadataRepository.repositoryTag,
  ]) {
    final repository =
        component.metadata[tag] as InferredTypeMetadataRepository?;
    if (repository == null) {
      continue;
    }
    for (final MapEntry<TreeNode, InferredType> entry
        in repository.mapping.entries.toList(growable: false)) {
      final Constant? constant = entry.value.constantValue;
      if (constant is StringConstant && values.contains(constant.value)) {
        repository.mapping[entry.key] = _withoutConstantValue(entry.value);
      }
    }
  }
}

InferredType _withoutConstantValue(InferredType type) => InferredType(
  type.exactType,
  type.concreteClass,
  type.nullable,
  type.isInt,
  null,
  type.closureMember,
  type.closureId,
  skipCheck: type.skipCheck,
  receiverNotInt: type.receiverNotInt,
);

/// Registers a library generated by a pass with the parts of the snapshot
/// that are keyed by library rather than by AST node.
///
/// Without this the snapshot is written just fine and even runs under the
/// JIT, but `gen_snapshot` rejects it: a library has to belong to a loading
/// unit, and every library needs a source entry, if only an empty one, for
/// the URI the AOT compiler puts in its debugging information.
void registerGeneratedLibrary(Component component, Library library) {
  component.uriToSource[library.fileUri] = Source(
    <int>[0],
    Uint8List(0),
    library.importUri,
    library.fileUri,
  );
  _addToRootLoadingUnit(component, library);
}

/// Adds [library] to the root loading unit of [component], if the snapshot
/// carries loading unit metadata.
///
/// Deferred loading splits the libraries over loading units, and a generated
/// library can be referenced from any of them, so it goes into the root unit,
/// which every other unit descends from.
void _addToRootLoadingUnit(Component component, Library library) {
  final repository =
      component.metadata[LoadingUnitsMetadataRepository.repositoryTag]
          as LoadingUnitsMetadataRepository?;
  final LoadingUnitsMetadata? metadata = repository?.mapping[component];
  if (metadata == null || metadata.loadingUnits.isEmpty) {
    return;
  }
  final LoadingUnit root = metadata.loadingUnits.firstWhere(
    (LoadingUnit unit) => unit.parentId == 0,
    orElse: () => metadata.loadingUnits.first,
  );
  root.libraryUris.add(library.importUri.toString());
}
